### ISSUE TITLE
fmt.Errorf misuse

### ISSUE THREAD

**Issue by fhs** [huin/chunkymonkey#19]
fmt.Errorf doesn't do what the code thinks it does. See http://golang.org/pkg/fmt/#Errorf

$ grep -nr fmt.Errorf src/
src/inspectlevel/inspectlevel.go:70:        fmt.Errorf("Error loading world: %s\n", err)
src/inspectlevel/inspectlevel.go:79:        fmt.Errorf("Error loading chunk: %s\n", err)

**Comment by huin** [comment]
Thanks, I only recently learned what the function did through an unrelated project - forgot I'd used it there.
