### ISSUE TITLE
Implement chat sanitization

### ISSUE THREAD

**Issue by huin** [huin/chunkymonkey#26]
Clients can be crashed if sent malformed color codes or over-long messages via chat. This should be prevented.

**Comment by ghost** [comment]
I implemented checking of color-tags and illegal characters in a chat message for WriteChatMessage() in proto.go .
You wrote a TODO item in the readChatMessage() function "// TODO sanitize chat message", do we need to check what clients write as well? I guess it makes sense if different types of clients connect to the server and one sends "illegal" chars or color-tags which could crash the main client.

**Comment by huin** [comment]
It wouldn't be a bad idea to do that at all, no. Should probably create issues that limit the amount of data that clients can send to the server in a packet, if for no other reason than stopping them from being able to make the server allocate lots of memory... One such place is in the chat messages from the client. This could be an issue in its own right, however.

**Comment by ghost** [comment]
Fixed with commit 4863198645a512ca1f42 . Both write and read ChatMessage functions are checked against illegal chars and color tag endings.
