### ISSUE TITLE
Change channel usage to check for closed channels

### ISSUE THREAD

**Issue by huin** [huin/chunkymonkey#29]
Release 57 brings in channel-read time checking for if a channel is closed. The current use of channels should be checked to see if there are places where this could benefit the codebase.

http://golang.org/doc/devel/release.html#r57

**Comment by ghost** [comment]
I could cleanup the channel code.

**Comment by huin** [comment]
Feel free to grab the issue if you want to do it, thanks :)

**Comment by ghost** [comment]
I checked all code and couldn't find a closed() function in use.
I also checked the player code if I could somewhere include checks against closed channels. I commit it in https://github.com/huin/chunkymonkey/commit/fab87d27f5d2a423ec9e5c98581b59ec42c4e410 but I don't know if this is what you thought about.

**Comment by huin** [comment]
That might well be enough for now - I feel that it would be better to use close(c) to indicate end-of-data rather than putting nil down it as I currently do in player.go. This is a pattern that needs some improvement when it comes to closing down goroutines (e.g chunk goroutine when the chunk is unloaded).

However, I'm not clear what to do about avoiding a send from panicing if a channel is closed and an attempt is made to send a value down it - is there a syntax for sending as well as receiving?

**Comment by ghost** [comment]
This is related to https://github.com/huin/chunkymonkey/issues/30 .
Changing goroutine/channel related code before closing issue #30 is kinda pointless since issue #30 will probably rewrite or change a lot of the related code.
Since the code compiles I am closing this issue.

**Comment by huin** [comment]
Agreed.
