### ISSUE TITLE
Discuss: Reassess server concurrency design

### ISSUE THREAD

**Issue by huin** [huin/chunkymonkey#30]
The current design makes use of both synchronous locking mechanisms, and also passing functions via channels. This could likely stand some improvement. I don't have clear ideas about what shape it should take, but I'd like to foster some discussion about how to:
- Achieve a design that is easy to understand and to add features into.
- Avoid race conditions and deadlock.
- Enables movement towards a decentralized server architecture that can run a world across multiple hosts.

Go should provide some very good concurrency patterns that can be utilized, but I feel that it's being used in a very cludgy way.

**Comment by ghost** [comment]
I would avoid locks and use channels only. This would probably mean one goroutine is the maximum for one object(struct). I would use a "update" function to go through each incoming channel data and pass processed data out through a channel. Time based function could be triggered with time.Tick(ns).
Scaling over multiple hosts could be implemented with the package netchan. This way we could export none time related data processing to different hosts.
I could provide a small pseudo code sample.

golang.org has an example on this here goroutines without locks: http://golang.org/doc/codewalk/sharemem/

**Comment by huin** [comment]
Agreed. As soon as I imported "sync" the first time I felt that I was going down the wrong path. Locks are feeling rather clumsy. Which is, in part, the reason I'm bringing this issue up (I still feel relatively new to Go in respect to applying correct design patterns).

Pseudo code examples would be handy.

There are a few places in the code where some sort of transaction/synchronization is required - particularly in regard to:
- Block state/type modification.
- Item pickup.
- Inventory changes.

A particularly nasty example of a problem to solve is the case of a player picking an item up. The chunk goroutine realises that the player is in pickup range of an item, and synchronously offers it to them. The player (in this synchronization) either takes the item (or some portion of it!) and returns control to the chunk. Ideally this is solved in such a way that:
- items can't be duped (e.g between two players in range of the same item at the same time),
- without introducing too much latency to the chunk goroutine.

The current implementation is probably _correct_ in terms of non-duping, but is a pain point for future scaling - heading down the channels-only route is likely to take us in the right direction IMO.

**Comment by huin** [comment]
Actually, my biggest fear at the moment is running the code into a deadlock situation. The communication graph at the moment is cyclic - which I'm fairly sure increases the likelihood of deadlocking. However, given that communication needs to happen from players to chunks _and_ vice-versa, I don't think that the cyclic nature of things is avoidable (at least, not without significantly re-thinking the goroutine assignments).

**Comment by ghost** [comment]
A simple example of the handling of goroutines and channels I meant https://gist.github.com/962537
The problem for me is, I don't know the code and it's structure. Same goes for the goroutines. Overall I don't have a good overview of the implementation.
So I can't really suggest anything specific.

**Comment by huin** [comment]
It's a decent enough example. I've been thinking of something similar for the chunks when it comes to doing things like the block automata and furnace timers etc. - the time/channel recv. pattern will be very useful there.

In the player I'm unsure if it's possible (or desireable) to reduce the goroutines per-se... However:
- The transmit loop is harmless, as it just consumes from the queue and writes to a TCP connection and doesn't touch anything else. Blocking on connection writes therefore doesn't cause blocking in the rest of the player logic (unless the txQueue fills up - at which point maybe we're sending too much data or the client needs to be kicked). Unfortunately I don't think we can put writes to a TCP socket in a select {} construct.
- The receive loop has a similar problem, in that it receives from a TCP socket and not from a selectable channel. However, we can arrange for it to put these messages onto a queue for the player mainloop. Unfortunately the TCP read and player mainloop cannot be in the same goroutine, unless we make the protocol code non-blocking - although throwing a goroutine at the problem doesn't look to be a Go anti-pattern to me.

So - I think we can remove the use of player locks from the Player.Packet\* methods with the introduction of a channel and proper handling. There are locks in other places in Player, but those can probably be replaced with something like in  your gist.

**Comment by ghost** [comment]
Another idea would be to use channels like events.
Like there: https://gist.github.com/962587
The problem is handling functions which get a value, like Player.GetName() string .
The best solution in this example is to make everything channel based so no calling of Get\* function is necessary.

**Comment by ghost** [comment]
You could do something like this:
A goroutine for each TCP connection which reads and writes from the socket. Write and read data is collected/send through two channels.
Example from one of my projects: https://gist.github.com/962615

Edit:
I forgot to say/include that all channels could be made buffered. With buffered channels most waiting for free channels can be avoided.

**Comment by huin** [comment]
Awesome - I'll take a look at these this evening :)

**Comment by nictuku** [comment]
More or less related to this, I think we should set our scalability targets more clearly. How many users in a server do we want to support?

I'd vote for 1000 concurrent users as a target. We could mention this explicitly in the "Intent" section of the design doc. It would bring more interest to our project.

**Comment by ghost** [comment]
I would say as many as the machine can handle. And if it can't handle more a second machine is used. Isn't this the goal of chunkymonkey to scale across different machines?
So if you are a Minecraft admin and you reached the limit of the amount of users your server can handle you just rent another one and add it to the "pool".

**Comment by huin** [comment]
With a good distributed architecture, we should be able to achieve very high numbers of people in a world by sharding by world location (effectively unlimited, at least in comparison to existing MC servers). Of course, when it comes down to a locality "shard" there will have to be much more limited numbers before a locality becomes overloaded.

1000 concurrent users in a world sounds reasonable initially, without having done any math on the subject... Should we quantify that further with hardware requirements?

**Comment by nictuku** [comment]
We need to get more data before determining specific hardware requirements. I don't know how much CPU/RAM a busy notchian server uses. 

In the meantime, we could project something like:

If one notchian server with 100 concurrent users uses X CPU, we want at most 10 times X - already considering the synchronization overhead of having multiple servers.

We'll probably have an efficient use of RAM too, considering the data won't be duplicated in several servers.

**Comment by huin** [comment]
If it helps, chunkymonkey uses <1/10th the CPU of the notchian server at the moment for just the one idlish connected player. Although that's likely due in large part to the missing features of active things like mobs and block behaviour. I assume that the notchian server wasn't generating terrain at the time as it had had plenty of time to stabilise after I logged into it.

**Comment by huin** [comment]
I think I'll hold off coding for a day or so while I write down a bunch of "processes" that need to occur in running servers (particularly chunk servers where most of the action happens), and how they interact - so that we have a fair overview of what it is that needs wiring up. I think this could be a key aspect of deciding on concurrency models.

**Comment by nictuku** [comment]
That's a great idea.

**Comment by huin** [comment]
I've added processes.md with an initial set of game processes that come to mind.

**Comment by huin** [comment]
I've been tinkering with some toy code to see how netchan works (quite a neat thing, it turns out), but ran into what appeared to be a possible bug in the package - so I've raised http://code.google.com/p/go/issues/detail?id=1805

Assuming that it is a bug, it'll be good to have this working in an expected manner when it comes to distributing the server... netchan looks like a promising package. Although we'll need to look into arranging the architecture better than I have been - throwing away locks in favour of channels, etc.

**Comment by huin** [comment]
As an update: nictuku and I had a chat on IRC and decided to take the following actions:
- Reduce the number of goroutines for chunk handling by putting chunks into "chunk shards", and having one goroutine per shard.
- Move the core player data and logic to run inside the chunk shard that the player is currently within (leaving the client handling code to relay events to the chunk shards and back).

It's a big refactoring, but it should reduce some of the issues of how players interact with chunks.

**Comment by huin** [comment]
Marking this as done... Have made a large set of refactorings to make the code more ready for a distributed environment.

**Comment by nictuku** [comment]
Very well done!
