### ISSUE TITLE
Let players drop items

### ISSUE THREAD

**Issue by nictuku** [huin/chunkymonkey#41]
In a notchian server, pressing Q with a item in hand results in the item being dropped - or more properly, thrown.

This currently doesn't work in chunkymonkey.

**Comment by nictuku** [comment]
The only packet involved here is:

2011/05/13 21:52:49.128080 (C->S) PacketPlayerBlockHit(status=4, blockLoc=&{0 0 0}, face=0)

But the server obviously has to keep track of that item. When a user reconnects after dropping an item, she sees:

2011/05/13 21:57:44.747217 (S->C) PacketItemSpawn(entityId=110080, itemId=268, count=1, data=31, location=&{-2315 2148 611}, orient
ation=&{0 0 0})

**Comment by nictuku** [comment]
No, after the player does a BlockHit, the following actions happen on the server:

2011/05/13 22:46:04.666135 (S->C) PacketItemSpawn(entityId=8277, itemId=3, count=1, data=0, location=&{-1332 2154 782}, orientation
=&{255 235 22})
2011/05/13 22:46:04.666509 (S->C) PacketEntityVelocity(entityId=8277, velocity=&{-76 -1353 1396})
2011/05/13 22:46:05.557298 (S->C) PacketEntityRelMove(entityId=8277, movement=&{-2 -38 34})
2011/05/13 22:46:06.565273 (S->C) PacketEntityRelMove(entityId=8277, movement=&{0 0 0})
2011/05/13 22:46:06.666128 (S->C) PacketItemCollect(collectedItem=8277, collector=8210)
2011/05/13 22:46:06.671214 (S->C) PacketEntityDestroy(entityId=8277)

(I missed these S->C parts beacuse intercept is getting confused sometimes and stops recording. I have a hint that it's the SignUpdate stuff that is fscking the parser)

**Comment by huin** [comment]
https://github.com/huin/chunkymonkey/blob/master/src/chunkymonkey/types.go#L176 <- for DigDropItem (the whole type might be regarded as badly named, that and the packet - mostly the packet names are from the wiki, however)

Note that it's probably best to ignore the item ID, count and data and use player.inventory.TakeOneHeldItem() to take an item into an empty slot.Slot object (that has been .Init()'d to make it properly empty) - this avoids item creation hacking by crafted packets. (Actually, come to think of it - the default values for a slot.Slot are correct "empty" values without the need for a .Init() call.)

**Comment by nictuku** [comment]
Yes, I'm using TakeOneHeldItem().

I'm currently struggling with how to get the player position, again.
chunk.subscriberPos isn't helping in this case.

On Fri, May 13, 2011 at 11:26 PM, huin
reply@reply.github.com
wrote:

> https://github.com/huin/chunkymonkey/blob/master/src/chunkymonkey/types.go#L176 <- for DigDropItem (the whole type might be regarded as badly named, that and the packet - mostly the packet names are from the wiki, however)
> 
> Note that it's probably best to ignore the item ID, count and data and use player.inventory.TakeOneHeldItem() to take an item into an empty slot.Slot object (that has been .Init()'d to make it properly empty) - this avoids item creation hacking by crafted packets. (Actually, come to think of it - the default values for a slot.Slot are correct "empty" values without the need for a .Init() call.)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/huin/chunkymonkey/issues/41#comment_1157457

## 

Yves Junqueira http://cetico.org/about

**Comment by nictuku** [comment]
Ah, of course. The current chunk is bogus, (the "BlockHit" has a bogus
chunk location in this case), so there are no subscribers.

On Sat, May 14, 2011 at 12:15 AM, Yves Junqueira
yves.junqueira@gmail.com wrote:

> Yes, I'm using TakeOneHeldItem().
> 
> I'm currently struggling with how to get the player position, again.
> chunk.subscriberPos isn't helping in this case.
> 
> On Fri, May 13, 2011 at 11:26 PM, huin
> reply@reply.github.com
> wrote:
> 
> > https://github.com/huin/chunkymonkey/blob/master/src/chunkymonkey/types.go#L176 <- for DigDropItem (the whole type might be regarded as badly named, that and the packet - mostly the packet names are from the wiki, however)
> > 
> > Note that it's probably best to ignore the item ID, count and data and use player.inventory.TakeOneHeldItem() to take an item into an empty slot.Slot object (that has been .Init()'d to make it properly empty) - this avoids item creation hacking by crafted packets. (Actually, come to think of it - the default values for a slot.Slot are correct "empty" values without the need for a .Init() call.)
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/huin/chunkymonkey/issues/41#comment_1157457
> 
> ## 
> 
> Yves Junqueira http://cetico.org/about

## 

Yves Junqueira http://cetico.org/about

**Comment by nictuku** [comment]
Work ongoing in https://github.com/nictuku/chunkymonkey/tree/drop-item 

The prototype kind of works, but it's not there yet.

**Comment by huin** [comment]
The thing to do might be to get the player code to recognize the status 4, create an item from the held item (if anything), then position it in front of the player's head with a small velocity away from the player, then work out the chunk that that item is in and add it to that chunk. Most of the work will occur atomically inside the player, and the chunk can then just accept the new item asynchronously.

**Comment by jnwhiteh** [comment]
Any update on the issues with intercept that you note here? I'm having the same problem where I don't record those packets (although I record others afterwards, but I only see the PacketPlayerBlockHit). I was going to look at this issue but ran into a bit of a wall =)

**Comment by huin** [comment]
Was this a question for me?

**Comment by jnwhiteh** [comment]
Not unless you know the answer, I'm addressing the issue nictuku raises above where intercept is missing these additional packets. Either that or its a red herring, just trying to see about getting this finally implemented now that we have inventory loading working.

**Comment by huin** [comment]
I don't believe that it's missing packets. It certainly cannot 'miss' a
packet without losing sync on the whole stream. It might not be reporting
packets on the log, although I think that's unlikely.

**Comment by jnwhiteh** [comment]
Alright, well when I see a dropped item I see the singular packet that he's reporting and none of the others. I guess I'll run with that then.

**Comment by jnwhiteh** [comment]
This has been implemented in 858a6edcbef785993d74. Thanks to nictuku for the original code, huin for working out the proper vector!
