### ISSUE TITLE
proposal: new directory layout

### ISSUE THREAD

**Issue by nictuku** [huin/chunkymonkey#45]
My proposal:

src/chunkymonkey:
*block
*chunk
*chunkstore
*inventory
*itemtype
*mob
*nbt
*player
*recipe
entity.go
game.go
gamerules.go
interfaces.go
item.go
physics.go
physics_test.go
proto.go
proto_test.go
record.go
server_auth.go
slot.go
slot_test.go
types.go
types_test.go
worldstore.go

src/main:
chunkymonkey.go

src/util:
*datatests
*dumpblockdefs
*inspectlevel
*intercept

You can see a preview here:
https://github.com/nictuku/chunkymonkey/tree/directories-fix

I think this looks much better. Are you folks OK with this layout? Then I'll spend more time on this. Just FYI there are two problems with my current change:

1) for some reason godag is only being able to compile the whole tree, not individual pieces.
gd # works
gd src # works
gd src/chunkymonkey # does not work, even if I see various -L and -I parameters

2) before running tests (gd -t) I _always_ have to do gd -c. 

gd -c ; gd -t ; works
gd -c ; gd ; gd -t # does not work

I'll contact godag folks about this later.

**Comment by nictuku** [comment]
I found solutions for the problems I mentioned, so I'm pushing this to my repo and will open a pull request. The sooner we do this the better, since it can be disruptive to our various branches.

**Comment by huin** [comment]
Looks good.

On the test side of things: I've had that trouble as well, although `make test` should work... at least, it has for me in the past.

**Comment by huin** [comment]
Note that I see a broken unit test relating to the creeper spawn still, despite the fix. Looks like some metadata bytes changed.

```
--- FAIL: mob.TestMobSpawn (0.00 seconds)
Resulting raw data mismatch for creeper spawn, wanted:
    "\x18\x00\x00\x1ea2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8d\x00\x01\x10\xff\x11\x01\x7f\x1c\x00\x00\x1ea\x00\x00\x00\x00\x00\x00"
    but got: 
    "\x18\x00\x00\x1ea2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8d\x00\x01\x11\x01\x10\xff\x7f\x1c\x00\x00\x1ea\x00\x00\x00\x00\x00\x00"
FAIL
```

**Comment by nictuku** [comment]
hmm that's odd. It works for me..

**Comment by huin** [comment]
Ah, my bad. My tree was probably in an odd state.
