### ISSUE TITLE
Load player inventory from chunk store

### ISSUE THREAD

**Issue by jnwhiteh** [huin/chunkymonkey#69]

**Comment by jnwhiteh** [comment]
I'll probably take a cue from what you did with position, etc. and write a nbt function to read in an inventory in the hopes that it can be re-used for chests, dispensers, furnaces, etc. I'll do some investigation first to get a better idea, of course =)

**Comment by huin** [comment]
I'm pondering other things like having converting to/from NBT as methods on mobs etc. - although undecided.

**Comment by jnwhiteh** [comment]
Seems like perhaps we could have an interface for nbt.Reader and nbt.Writer? Then I could implement those methods for Inventory, Entities, etc. Just a thought.

**Comment by huin** [comment]
Actually that sounds like the right direction to be going. There's obviously going to have to be a sense of context for them. Hm. This actually sounds like we might have a nice recursive model of sorts... Chunks would implement it, the things inside chunks would implement it as well, which provides appropriate context - chunks know their own NBT structure, and thus when to delegate parts of their NBT to child readers/writers (also, so might players and their inventory, and at some level, the game would implement it as well - although I doubt that much would implement it inside that).

It does however imply that anything that implements it is somewhat tied to the storage version. This probably isn't a bad thing, however. I think that the NBT structure used by MC has stayed relatively constant from version to version [citation needed].
