### ISSUE TITLE
Giving player 64 (door)

### ISSUE THREAD

**Issue by ghost** [huin/chunkymonkey#71]
Giving a player 64 (door) gives him the bottom of a door instead of a complete door.
This could be a nice feature for garden doors (small doors). I don't know if this is a bug in the client or in our server.
I will test it with the standard server at some time.

**Comment by huin** [comment]
Cooincidently enough I noticed something similar last night while manually testing some things. I fixed the door recipes, which were emitting the blocks, but not the door items. I've just pushed this. Item 64 doesn't really make sense to be in the inventory under normal circumstances, but item 324 does. However, this obviously means that we need to implement item placement where the item creates block(s) that are not the same ID as the item itself.

**Comment by jnwhiteh** [comment]
64 is the data value for the bottom half of the door. This matches the behaviour on the Notchian server, so I'm closing this issue.
