### ISSUE TITLE
a crash w/ stack trace

### ISSUE THREAD

**Issue by skelterjohn** [huin/chunkymonkey#86]
calypso:chunkymonkey jasmuth$ bin/chunkymonkey w1/
2011/10/17 16:08:43 Connection closed server list poll
2011/10/17 16:08:46 Client 127.0.0.1:65395 connected as skelterjohn
2011/10/17 16:08:46 Client 127.0.0.1:65395 passed minecraft.net authentication
2011/10/17 16:08:57 Couldn't place a leaf block (255,75,7)
2011/10/17 16:08:57 Couldn't place a leaf block (255,75,8)
2011/10/17 16:08:57 Couldn't place a leaf block (255,75,9)
2011/10/17 16:08:57 Couldn't place a leaf block (255,75,10)
2011/10/17 16:08:57 Couldn't place a leaf block (255,75,11)
2011/10/17 16:08:59 Couldn't place a leaf block (255,71,6)
2011/10/17 16:08:59 Couldn't place a leaf block (255,71,7)
2011/10/17 16:08:59 Couldn't place a leaf block (255,71,8)
2011/10/17 16:08:59 Couldn't place a leaf block (255,71,9)
2011/10/17 16:08:59 Couldn't place a leaf block (255,71,10)
2011/10/17 16:09:05 Couldn't place a leaf block (1,69,16)
2011/10/17 16:09:05 Couldn't place a leaf block (2,69,16)
2011/10/17 16:09:05 Couldn't place a leaf block (3,69,16)
2011/10/17 16:09:05 Couldn't place a leaf block (4,69,16)
2011/10/17 16:09:05 Couldn't place a leaf block (5,69,16)
2011/10/17 16:09:06 ChunkShard[types.ShardXz{X:0, Z:-1}/types.ChunkXz{X:0, Z:-16}]: Writing chunks.
2011/10/17 16:09:10 Couldn't place a leaf block (255,74,8)
2011/10/17 16:09:10 Couldn't place a leaf block (255,74,9)
2011/10/17 16:09:10 Couldn't place a leaf block (255,74,10)
2011/10/17 16:09:10 Couldn't place a leaf block (255,74,11)
2011/10/17 16:09:10 Couldn't place a leaf block (255,74,12)
2011/10/17 16:09:10 Couldn't place a leaf block (16,71,1)
2011/10/17 16:09:10 Couldn't place a leaf block (16,71,2)
2011/10/17 16:09:10 Couldn't place a leaf block (16,71,3)
2011/10/17 16:09:10 Couldn't place a leaf block (16,71,4)
2011/10/17 16:09:10 Couldn't place a leaf block (16,71,5)
2011/10/17 16:09:15 Couldn't place a leaf block (16,73,10)
2011/10/17 16:09:15 Couldn't place a leaf block (16,73,11)
2011/10/17 16:09:15 Couldn't place a leaf block (16,73,12)
2011/10/17 16:09:15 Couldn't place a leaf block (16,73,13)
2011/10/17 16:09:15 Couldn't place a leaf block (16,73,14)
2011/10/17 16:09:21 Couldn't place a leaf block (255,76,12)
2011/10/17 16:09:21 Couldn't place a leaf block (255,76,13)
2011/10/17 16:09:21 Couldn't place a leaf block (255,76,14)
2011/10/17 16:09:21 Couldn't place a leaf block (255,76,15)
2011/10/17 16:09:21 Couldn't place a leaf block (255,76,16)
2011/10/17 16:09:21 Couldn't place a leaf block (0,76,16)
2011/10/17 16:09:21 Couldn't place a leaf block (1,76,16)
2011/10/17 16:09:21 Couldn't place a leaf block (2,76,16)
2011/10/17 16:09:21 Couldn't place a leaf block (3,76,16)
2011/10/17 16:09:25 Couldn't place a leaf block (16,77,3)
2011/10/17 16:09:25 Couldn't place a leaf block (16,77,4)
2011/10/17 16:09:25 Couldn't place a leaf block (16,77,5)
2011/10/17 16:09:25 Couldn't place a leaf block (16,77,6)
2011/10/17 16:09:25 Couldn't place a leaf block (16,77,7)
2011/10/17 16:09:27 Couldn't place a leaf block (255,69,10)
2011/10/17 16:09:27 Couldn't place a leaf block (255,69,11)
2011/10/17 16:09:27 Couldn't place a leaf block (255,69,12)
2011/10/17 16:09:27 Couldn't place a leaf block (255,69,13)
2011/10/17 16:09:27 Couldn't place a leaf block (255,69,14)
2011/10/17 16:09:29 Couldn't place a leaf block (255,72,11)
2011/10/17 16:09:29 Couldn't place a leaf block (255,72,12)
2011/10/17 16:09:29 Couldn't place a leaf block (255,72,13)
2011/10/17 16:09:29 Couldn't place a leaf block (255,72,14)
2011/10/17 16:09:29 Couldn't place a leaf block (255,72,15)
2011/10/17 16:09:38 Couldn't place a leaf block (8,69,16)
2011/10/17 16:09:38 Couldn't place a leaf block (9,69,16)
2011/10/17 16:09:38 Couldn't place a leaf block (10,69,16)
2011/10/17 16:09:38 Couldn't place a leaf block (11,69,16)
2011/10/17 16:09:38 Couldn't place a leaf block (12,69,16)
panic: runtime error: index out of range

goroutine 21 [running]:
rand.(_rngSource).Int63(0xf840023400, 0xf840152540, 0xf84001a1e0, 0xf840023400)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rng.go:243 +0x7b
rand.(_Rand).Int63(0xf84001c560, 0x240c000, 0xbf853, 0xf84001c560)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:37 +0x43
rand.(_Rand).Int31(0xf84001c560, 0x10, 0x7ffff1bf00000000, 0xbf8d5)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:43 +0x25
rand.(_Rand).Int31n(0xf84001c560, 0x2710, 0xc, 0x5c0a9, 0xf84001c560, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:70 +0x53
rand.(_Rand).Intn(0xf84001c560, 0xf800002710, 0xf8448347e0, 0xe9708, 0xf840002220, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:80 +0x34
chunkymonkey/gamerules.(_SaplingAspect).Tick(0xf840002220, 0xf842c9be80, 0xf8448347e0, 0xf840150100, 0xf84513ee40, ...)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/gamerules/block_sapling.go:27 +0x30
chunkymonkey/shardserver.(_Chunk).blockTick(0xf84513ee40, 0xecaf1)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/chunk.go:511 +0x2d7
chunkymonkey/shardserver.(_Chunk).tick(0xf84513ee40, 0x1)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/chunk.go:439 +0x59
chunkymonkey/shardserver.(_ChunkShard).tick(0xf840187b00, 0x2491100)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/shard.go:91 +0x85
----- stack segment boundary -----
rand.(_rngSource).Int63(0xf840023400, 0xf840152540, 0xf84001a1e0, 0xf840023400)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rng.go:243 +0x7b
rand.(_Rand).Int63(0xf84001c560, 0x240c000, 0xbf853, 0xf84001c560)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:37 +0x43
rand.(_Rand).Int31(0xf84001c560, 0x10, 0x7ffff1bf00000000, 0xbf8d5)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:43 +0x25
rand.(_Rand).Int31n(0xf84001c560, 0x2710, 0xc, 0x5c0a9, 0xf84001c560, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:70 +0x53
rand.(_Rand).Intn(0xf84001c560, 0xf800002710, 0xf8448347e0, 0xe9708, 0xf840002220, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:80 +0x34
chunkymonkey/gamerules.(_SaplingAspect).Tick(0xf840002220, 0xf842c9be80, 0xf8448347e0, 0xf840150100, 0xf84513ee40, ...)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/gamerules/block_sapling.go:27 +0x30
chunkymonkey/shardserver.(_Chunk).blockTick(0xf84513ee40, 0xecaf1)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/chunk.go:511 +0x2d7
chunkymonkey/shardserver.(_Chunk).tick(0xf84513ee40, 0x1)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/chunk.go:439 +0x59
chunkymonkey/shardserver.(_ChunkShard).tick(0xf840187b00, 0x2491100)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/shard.go:91 +0x85
----- stack segment boundary -----
chunkymonkey/shardserver.(_ChunkShard).serve(0xf840187b00, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/shard.go:77 +0x7b
created by chunkymonkey/shardserver.(_LocalShardManager).getShard
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/localshardmgr.go:44 +0x125

goroutine 1 [select]:
chunkymonkey.(*Game).Serve(0xf840034d00, 0x6)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/game.go:104 +0x17f
main.main()
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/cmd/chunkymonkey/chunkymonkey.go:127 +0x7ac

goroutine 2 [syscall]:
syscall.Syscall6()
    /Users/jasmuth/Documents/userland/go/src/pkg/syscall/asm_darwin_amd64.s:38 +0x5
syscall.kevent(0x6, 0x0, 0x0, 0xf84002da88, 0x10000000a, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/syscall/zsyscall_darwin_amd64.go:165 +0x70
syscall.Kevent(0xf800000006, 0x0, 0x0, 0xf84002da88, 0xa0000000a, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/syscall/syscall_bsd.go:549 +0x8c
net.(_pollster).WaitFD(0xf84002da80, 0xf84015b380, 0x0, 0x7200000008, 0x0, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/fd_darwin.go:95 +0x115
net.(_pollServer).Run(0xf84015b380, 0x0)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/fd.go:228 +0xcb
created by net.newPollServer
    /Users/jasmuth/Documents/userland/go/src/pkg/net/newpollserver.go:36 +0x31f

goroutine 3 [select]:
chunkymonkey/chunkstore.(*ChunkService).Serve(0xf84015e700, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/chunkstore/chunkservice.go:40 +0x2da
created by chunkymonkey/worldstore.LoadWorldStore
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/worldstore/worldstore.go:78 +0x739

goroutine 4 [select]:
chunkymonkey/chunkstore.(*ChunkService).Serve(0xf84015e920, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/chunkstore/chunkservice.go:40 +0x2da
created by chunkymonkey/worldstore.LoadWorldStore
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/worldstore/worldstore.go:78 +0x739

goroutine 5 [select]:
chunkymonkey/chunkstore.(*ChunkService).Serve(0xf84015e980, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/chunkstore/chunkservice.go:40 +0x2da
created by chunkymonkey/worldstore.LoadWorldStore
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/worldstore/worldstore.go:90 +0x8c9

goroutine 6 [chan receive]:
net.(_pollServer).WaitRead(0xf84015b380, 0xf8400f1a00, 0x0, 0x0)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/fd.go:257 +0x52
net.(_netFD).accept(0xf8400f1a00, 0x492f6, 0x0, 0x0, 0x0, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/fd.go:628 +0x18c
net.(_TCPListener).AcceptTCP(0xf840171810, 0x2451f30, 0x0, 0x0, 0x8, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/tcpsock_posix.go:268 +0x71
net.(_TCPListener).Accept(0xf840171810, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/tcpsock_posix.go:278 +0x49
chunkymonkey.(*ConnHandler).run(0xf84015e9e0, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/connhandler.go:88 +0xa4
created by chunkymonkey.NewConnHandler
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/connhandler.go:72 +0x89

goroutine 7 [chan receive]:
net.(_pollServer).WaitRead(0xf84015b380, 0xf840196000, 0x0, 0x0)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/fd.go:257 +0x52
net.(_netFD).accept(0xf840196000, 0x492f6, 0x0, 0x0, 0x0, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/fd.go:628 +0x18c
net.(_TCPListener).AcceptTCP(0xf840171c38, 0x0, 0x0, 0x0, 0x18, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/tcpsock_posix.go:268 +0x71
net.(_TCPListener).Accept(0xf840171c38, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/tcpsock_posix.go:278 +0x49
http.(*Server).Serve(0xf840194080, 0xf84015b540, 0xf840171c38, 0x0, 0x0, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/http/server.go:956 +0x7a
http.Serve(0xf84015b540, 0xf840171c38, 0x0, 0x0, 0xf84015b540, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/http/server.go:923 +0x70
created by main.startHttpServer
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/cmd/chunkymonkey/chunkymonkey.go:73 +0xaa

goroutine 8 [select]:
time.tickerLoop()
    /Users/jasmuth/Documents/userland/go/src/pkg/time/tick.go:98 +0x284
created by time.startTickerLoop
    /Users/jasmuth/Documents/userland/go/src/pkg/time/tick.go:76 +0x46

goroutine 10 [runnable]:
time.wakeLoop(0xf840197190, 0xf8401971e0, 0x0, 0x0)
    /Users/jasmuth/Documents/userland/go/src/pkg/time/tick.go:83 +0x38
created by time.(*alarmer).set
    /Users/jasmuth/Documents/userland/go/src/pkg/time/tick.go:60 +0xa1

goroutine 16 [finalizer wait]:
created by runtime.gc
    /Users/jasmuth/Documents/userland/go/src/pkg/runtime/mgc0.c:914

goroutine 13 [chan receive]:
net.(_pollServer).WaitRead(0xf84015b380, 0xf8400f1be0, 0x800000001, 0x23ffffffff)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/fd.go:257 +0x52
net.(_netFD).Read(0xf8400f1be0, 0xf84004f8e0, 0x800000001, 0xf800000000, 0x0, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/fd.go:398 +0x1a4
net.(_TCPConn).Read(0xf8401b2040, 0xf84004f8e0, 0x800000001, 0xf840030200, 0x0, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/net/tcpsock_posix.go:74 +0x95
io.ReadAtLeast(0xf84015db40, 0xf8401b2040, 0xf84004f8e0, 0x800000001, 0x1, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/io/io.go:237 +0xc3
io.ReadFull(0xf84015db40, 0xf8401b2040, 0xf84004f8e0, 0x800000001, 0x3c47b8, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/io/io.go:256 +0x69
encoding/binary.Read(0xf84015db40, 0xf8401b2040, 0xf84003bcc0, 0x248cf00, 0x152800, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/encoding/binary/binary.go:132 +0xd1
chunkymonkey/proto.readPacketId(0xf84015db40, 0xf8401b2040, 0x23a848, 0x0, 0x0, ...)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/proto/proto.go:3175 +0xcc
chunkymonkey/proto.ServerReadPacket(0xf84015db40, 0xf8401b2040, 0xf8401bd000, 0xf8401b5000, 0x0, ...)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/proto/proto.go:3210 +0x45
chunkymonkey/player.(_Player).receiveLoop(0xf8401b5000, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/player/player.go:561 +0xb1
created by chunkymonkey/player.(*Player).Run
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/player/player.go:301 +0x11e

goroutine 14 [chan receive]:
chunkymonkey/player.(_Player).transmitLoop(0xf8401b5000, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/player/player.go:573 +0x35
created by chunkymonkey/player.(_Player).Run
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/player/player.go:302 +0x135

goroutine 15 [select]:
chunkymonkey/player.(_Player).mainLoop(0xf8401b5000, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/player/player.go:711 +0x50c
created by chunkymonkey/player.(_Player).Run
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/player/player.go:303 +0x14c

goroutine 17 [runnable]:
chunkymonkey/shardserver.(_ChunkShard).serve(0xf840186900, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/shard.go:75 +0xdd
created by chunkymonkey/shardserver.(_LocalShardManager).getShard
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/localshardmgr.go:44 +0x125

goroutine 25 [syscall]:
syscall.Syscall6()
    /Users/jasmuth/Documents/userland/go/src/pkg/syscall/asm_darwin_amd64.s:38 +0x5
syscall.Select(0x0, 0x0, 0x0, 0x0, 0xf84715d010, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/syscall/zsyscall_darwin_amd64.go:737 +0x63
syscall.Sleep(0x3b9aca00, 0x0, 0x145016a8, 0x0)
    /Users/jasmuth/Documents/userland/go/src/pkg/syscall/syscall_bsd.go:142 +0x7a
time.sysSleep(0x3b9aca00, 0x0, 0x0, 0xf840106100)
    /Users/jasmuth/Documents/userland/go/src/pkg/time/sys_unix.go:15 +0x25
time.sleeper(0x1, 0x0)
    /Users/jasmuth/Documents/userland/go/src/pkg/time/sleep.go:128 +0xa9
created by time.after
    /Users/jasmuth/Documents/userland/go/src/pkg/time/sleep.go:109 +0x1c7

goroutine 19 [running]:
chunkymonkey/shardserver.(_ChunkShard).serve(0xf840188400, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/shard.go:77 +0x7b
created by chunkymonkey/shardserver.(_LocalShardManager).getShard
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/localshardmgr.go:44 +0x125

goroutine 23 [select]:
chunkymonkey/shardserver.(_ChunkShard).serve(0xf840187200, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/shard.go:75 +0xdd
created by chunkymonkey/shardserver.(_LocalShardManager).getShard
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/localshardmgr.go:44 +0x125
panic: runtime error: index out of range

goroutine 19 [running]:
rand.(_rngSource).Int63(0xf840023400, 0xf840152540, 0xf84001a1e0, 0xf840023400)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rng.go:243 +0x7b
rand.(_Rand).Int63(0xf84001c560, 0x240ef70, 0xbf853, 0xf84001c560)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:37 +0x43
rand.(_Rand).Int31(0xf84001c560, 0x10, 0x7ffff1bf00000000, 0xbf8d5)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:43 +0x25
rand.(_Rand).Int31n(0xf84001c560, 0x2710, 0xc, 0x5c0a9, 0xf84001c560, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:70 +0x53
rand.(_Rand).Intn(0xf84001c560, 0xf800002710, 0xf844834950, 0xe9708, 0xf840002220, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:80 +0x34
chunkymonkey/gamerules.(_SaplingAspect).Tick(0xf840002220, 0xf842c941c0, 0xf844834950, 0xf840150100, 0xf84044ca80, ...)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/gamerules/block_sapling.go:27 +0x30
chunkymonkey/shardserver.(_Chunk).blockTick(0xf84044ca80, 0xecaf1)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/chunk.go:511 +0x2d7
chunkymonkey/shardserver.(_Chunk).tick(0xf84044ca80, 0x1)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/chunk.go:439 +0x59
chunkymonkey/shardserver.(_ChunkShard).tick(0xf840188400, 0x2490100)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/shard.go:91 +0x85
----- stack segment boundary -----
rand.(_rngSource).Int63(0xf840023400, 0xf840152540, 0xf84001a1e0, 0xf840023400)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rng.go:243 +0x7b
rand.(_Rand).Int63(0xf84001c560, 0x240ef70, 0xbf853, 0xf84001c560)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:37 +0x43
rand.(_Rand).Int31(0xf84001c560, 0x10, 0x7ffff1bf00000000, 0xbf8d5)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:43 +0x25
rand.(_Rand).Int31n(0xf84001c560, 0x2710, 0xc, 0x5c0a9, 0xf84001c560, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:70 +0x53
rand.(_Rand).Intn(0xf84001c560, 0xf800002710, 0xf844834950, 0xe9708, 0xf840002220, ...)
    /Users/jasmuth/Documents/userland/go/src/pkg/rand/rand.go:80 +0x34
chunkymonkey/gamerules.(_SaplingAspect).Tick(0xf840002220, 0xf842c941c0, 0xf844834950, 0xf840150100, 0xf84044ca80, ...)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/gamerules/block_sapling.go:27 +0x30
chunkymonkey/shardserver.(_Chunk).blockTick(0xf84044ca80, 0xecaf1)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/chunk.go:511 +0x2d7
chunkymonkey/shardserver.(_Chunk).tick(0xf84044ca80, 0x1)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/chunk.go:439 +0x59
chunkymonkey/shardserver.(_ChunkShard).tick(0xf840188400, 0x2490100)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/shard.go:91 +0x85
----- stack segment boundary -----
chunkymonkey/shardserver.(_ChunkShard).serve(0xf840188400, 0x0)
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/shard.go:77 +0x7b
created by chunkymonkey/shardserver.(_LocalShardManager).getShard
    /Users/jasmuth/Dropbox/gospace/chunkymonkey/src/chunkymonkey/shardserver/localshardmgr.go:44 +0x125

**Comment by huin** [comment]
Commit d876da4048e0b20d130d2f5c953b196b7a64aad6 should fix this. Reopen if this crops up again, but it's a race condition so might not.
